version: '3.4'
services:
  api:
    image: docker.strobes.co/strobes-api:latest
    depends_on:
      - rabbitmq
      - postgres
    command:  sh start_api.sh
    expose:
      - 8000
    env_file:
      - ./api.env
    environment:
      - CONTAINER=web
    restart: always

  celery:
    image: docker.strobes.co/strobes-api:latest
    command: sh start_celery.sh
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./api.env
    environment:
      - CONTAINER=celery
    restart: always

  frontend:
    image: docker.strobes.co/strobes-fe:latest
    command: bash -c 'serve -s build -l 3000'
    expose:
      - 3000
    restart: always

  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
      - frontend

  postgres:
    image:  postgres:10.5-alpine
    expose:
      - 5432
    env_file:
      - ./api.env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.3-alpine
    labels:
      NAME: rabbitmq
    volumes:
      - ./rabbitmq_config/:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq
    expose:
      - 5672
    restart: always
    
  elasticsearch:
    image: elasticsearch:7.7.0
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
  
  logstash:
    image: logstash:7.7.0
    volumes:
      - ./logstash/:/logstash/
    command: logstash -f /logstash/logstash.conf
    depends_on:
      - elasticsearch
    expose:
      - 5959
    restart: always
  
  triangulum:
    image: docker.strobes.co/triangulum:latest
    hostname: "triangulum"
    expose:
      - 50051
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - triangulum_output:/output/
    depends_on:
      - rabbitmq
      - elasticsearch
    env_file:
      - ./triangulum.env
    restart: always


volumes:
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local
  esdata:
    driver: local
  logstash_data:
    driver: local
  triangulum_output:
    name: triangulum_output
    driver: local
