version: '2.0'
services:
  api:
    image: docker.strobes.co/strobes-api:latest
    depends_on:
      - rabbitmq
      - postgres
    command:  sh start_api.sh
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - CONTAINER=web
    restart: always

  celery:
    image: docker.strobes.co/strobes-api:latest
    command: sh start_celery.sh
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env
    environment:
      - CONTAINER=celery
    restart: always

  frontend:
    image: docker.strobes.co/strobes-fe:latest
    command: bash -c 'serve -s build -l 3000'
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: always

  nginx:
    image: docker.strobes.co/strobes-nginx:latest
    ports:
      - 80:80
    environment:
      - API_SCHEME=http
      - API_HOSTNAME=api
      - API_PORT=8000
      - APP_SCHEME=http
      - APP_HOSTNAME=frontend
      - APP_PORT=3000
      - NGINX_PORT=80
    depends_on:
      - api
      - frontend

  postgres:
    image:  postgres:10.5-alpine
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.3-alpine
    labels:
      NAME: rabbitmq
    volumes:
      - ./rabbitmq_config/:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq
    expose:
      - 5672
    restart: always


volumes:
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local
